# Generated by Django 5.1.7 on 2025-03-19 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_tax"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tax",
            options={"verbose_name_plural": "Tax"},
        ),
    ]
