# Generated by Django 5.1.7 on 2025-03-15 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "categoty", "verbose_name_plural": "categories"},
        ),
        migrations.RenameField(
            model_name="fooitem",
            old_name="category_name",
            new_name="category",
        ),
    ]
