# Generated by Django 5.1.7 on 2025-03-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooitem",
            name="description",
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
