# Generated by Django 5.1.7 on 2025-03-18 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_fooitem_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fooditems",
                to="menu.category",
            ),
        ),
    ]
